### PR TITLE
fix(glide.yaml): adding version to etcd dependency

### PR DESCRIPTION
**Pull request by arschles**

### CODE REVIEW

**Comment by mboersma** [comment]
LGTM. Should we sync up with etcd 2.2.2 in the [Dockerfile](https://github.com/deis/etcd/blob/master/rootfs/Dockerfile) too? It's on 2.2.1 currently.

**Comment by arschles** [comment]
@mboersma not sure how I feel upgrading the etcd version. basically I'm afraid it behaves differently and won't work in a containerized environment (I understand that a lot of work went into getting 2.2.1 working inside docker)

**Comment by mboersma** [comment]
> I'm afraid it behaves differently and won't work

It certainly ought to since it's just a patch release, but understood. Maybe glide should pin `github.com/coreos/etcd` at v2.2.1 then? (Or am I too preoccupied with consistency here?)

**Comment by arschles** [comment]
@mboersma you're right, may as well be consistent. pinned in https://github.com/arschles/etcd/commit/7ae58ac6a3b90a5bef3ef473b6478c6539742d11

**Pull request merged**
